// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetNamesHandlerFunc turns a function with the right signature into a get names handler
type GetNamesHandlerFunc func(GetNamesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNamesHandlerFunc) Handle(params GetNamesParams) middleware.Responder {
	return fn(params)
}

// GetNamesHandler interface for that can handle valid get names params
type GetNamesHandler interface {
	Handle(GetNamesParams) middleware.Responder
}

// NewGetNames creates a new http.Handler for the get names operation
func NewGetNames(ctx *middleware.Context, handler GetNamesHandler) *GetNames {
	return &GetNames{Context: ctx, Handler: handler}
}

/* GetNames swagger:route GET /get_names getNames

GetNames get names API

*/
type GetNames struct {
	Context *middleware.Context
	Handler GetNamesHandler
}

func (o *GetNames) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetNamesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
